#!/usr/bin/env bash
#
# Cortex, first phase init
#

_my_name=`basename $0`
if [ "`echo $0 | cut -c1`" = "/" ]; then
  _my_path=`dirname $0`
else
  _my_path=`pwd`/`echo $0 | sed -e s/$_my_name//`
fi

# Set up basic context
export SCRIPT=$_my_path/$_my_name
export PROJECT_NAME="cortex-testing node"
export DOT_FILE=${_my_path}/.project
export BINDIR=${_my_path}/bin
export VENV_PY=$(which python)
export GO_NAME="go.py"
export GO_PY=${_my_path}/$GO_NAME

# Set up django (useful to hijack the ORM)
export DJANGO_SETTINGS_MODULE="cortex.settings.django"

# HACK (to use development files for now)
#export PYTHONPATH=$PYTHONPATH:${_my_path}/../

# Enter python world, launching second phase init
echo "Launching $PROJECT_NAME"
echo " with Python=$VENV_PY"
echo " with my_path: $_my_path"
echo " with my_name: $_my_name"
echo
$VENV_PY $GO_PY "$@"
